export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';

export const ADD_EDIT_BOOK = 'ADD_EDIT_BOOK';
export const ADD_EDIT_BOOK_SUCCESS = 'ADD_EDIT_BOOK_SUCCESS';
export const ADD_EDIT_BOOK_FAILED = 'ADD_EDIT_BOOK_FAILED';

export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILED = 'DELETE_BOOK_FAILED';

export const FETCH_BOOKS_TAGS = 'FETCH_BOOKS_TAGS';
export const FETCH_BOOKS_TAGS_SUCCESS = 'FETCH_BOOKS_TAGS_SUCCESS';
export const FETCH_BOOKS_TAGS_FAILED = 'FETCH_BOOKS_TAGS_FAILED';

export const HANDLE_SEARCH = 'HANDLE_SEARCH';
